version: '3.4'

#services:
  # customers-api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://0.0.0.0:80
  #     # - IdentityUrl=http://identity-api
  #     # - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
  #     - SeqServerUrl=http://brainykatseq
  #   ports:
  #     - "5103:80"
  #     - "50001:50001"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  # customers-api-dapr:
  #   command: ["./daprd",
  #     "-app-id", "customers-api",
  #     "-app-port", "80",
  #     "-components-path", "/components",
  #     "-config", "/configuration/brainykat-config.yaml"
  #     ]
  #   volumes:
  #     - "./dapr/components/:/components"
  #     - "./dapr/configuration/:/configuration"

# services:
#   finance.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=https://+:443;http://+:80
#     ports:
#       - "80"
#       - "443"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

# services:
#   webstatus:
#     # environment:
#     #   - ASPNETCORE_ENVIRONMENT=Development
#     #   - ASPNETCORE_URLS=https://+:443;http://+:80
#     # ports:
#     #   - "80"
#     #   - "443"
#     # environment:
#     #   - ASPNETCORE_URLS=http://0.0.0.0:80
#     #   - HealthChecksUI__HealthChecks__0__Name=Customer API
#     #   - HealthChecksUI__HealthChecks__0__Uri=http://customers-api/hc
#     #   - HealthChecksUI__HealthChecks__1__Name=Finance API
#     #   - HealthChecksUI__HealthChecks__1__Uri=http://finance-api/hc
#       # - HealthChecksUI__HealthChecks__2__Name=Identity API
#       # - HealthChecksUI__HealthChecks__2__Uri=http://identity-api/hc
#       # - HealthChecksUI__HealthChecks__3__Name=Ordering API
#       # - HealthChecksUI__HealthChecks__3__Uri=http://ordering-api/hc
#       # - HealthChecksUI__HealthChecks__4__Name=Payment API
#       # - HealthChecksUI__HealthChecks__4__Uri=http://payment-api/hc
#       # - HealthChecksUI__HealthChecks__5__Name=Web Shopping Aggregator
#       # - HealthChecksUI__HealthChecks__5__Uri=http://webshoppingagg/hc
#       # - HealthChecksUI__HealthChecks__6__Name=Blazor UI Host
#       # - HealthChecksUI__HealthChecks__6__Uri=http://blazor-client/hc
#     ports:
#       - "5107:80"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

services:
  webbff-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SeqServerUrl=http://seq
      - BasketUrlHC=http://customers-api/hc
      - CatalogUrlHC=http://finance-api/hc
      #- IdentityUrlHC=http://identity-api/hc
    ports:
      - "5121:80"
      - "50007:50001"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webbffapigw:
    environment:
      - ENVOY_CUSTOMERS_API_ADDRESS=customers-api
      - ENVOY_CUSTOMERS_API_PORT=80
      - ENVOY_FINANCE_API_ADDRESS=finance-api
      - ENVOY_FINANCE_API_PORT=80
    ports:
      - "5202:80"
      - "15202:8001"
      - "50008:50001"

  webbffapigw-dapr:
    command: ["./daprd",
      "-app-id", "webbffapigw",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
