version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  brainykatseq:
    image: datalust/seq:latest
    container_name: brainykat-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8082:80"

  # # Use the Azure SQL Edge version so we can also run on Apple Sillicon (thanks @ChristianWeyer)
  brainykatsqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - brainykat-sqldata:/var/opt/mssql

  brainykatzipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"

  
  customers-api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Services/CustomerService/Customers.API/Dockerfile
    ports:
      - "5103:80"
      - "50001:50001" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://brainykatseq
    depends_on:
      - brainykatsqldata
    

  customers-api-dapr:
    #image: "daprio/daprd:latest"
    image: "daprio/daprd:1.9.4"
    network_mode: "service:customers-api"
    command: ["./daprd",
      "-app-id", "customers-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]    
    depends_on:
      - customers-api
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  finance-api:
    image: ${DOCKER_REGISTRY-}financeapi
    build:
      context: .
      dockerfile: src/Services/FinanceService/Finance.API/Dockerfile
    ports:
      - "5105:80"
      - "50003:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://brainykatseq
    depends_on:
      - brainykatsqldata
  
  finance-api-dapr:
    #image: "daprio/daprd:latest"
    image: "daprio/daprd:1.9.4"
    command: ["./daprd",
      "-app-id", "finance-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]
    network_mode: "service:finance-api"
    depends_on:
      - finance-api
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  webbff-api:
    image: ${DOCKER_REGISTRY-}webbffapi
    build:
      context: .
      dockerfile: src/APIGateways/Aggregators/WebBff.API/Dockerfile
    depends_on:
      - customers-api
      - finance-api

  webaggapi-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:webbff-api"
    command: ["./daprd",
      "-app-id", "webbff-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - webbff-api

  webbffapigw:
    image: ${REGISTRY:-eshopdapr}/webbffapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Envoy/Dockerfile

  webbffapigw-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:webbffapigw"
    depends_on:
      - webbffapigw

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile
    ports:
      - "5107:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Customers API
      - HealthChecksUI__HealthChecks__0__Uri=http://customers-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Finance API
      - HealthChecksUI__HealthChecks__1__Uri=http://finance-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Web BFF Aggregator
      - HealthChecksUI__HealthChecks__2__Uri=http://webbff-api/hc 


  dapr-placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"
        

volumes:
  brainykat-sqldata:
    external: false



