version: '3.4'

services:
  brainykatrabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"

  brainykatredis:
    image: redis:alpine
    ports:
      - "5379:6379"

  brainykatseq:
    image: datalust/seq:latest
    container_name: brainykat-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8082:80"

  # # Use the Azure SQL Edge version so we can also run on Apple Sillicon (thanks @ChristianWeyer)
  brainykatsqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - brainykat-sqldata:/var/opt/mssql

  brainykatzipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"

  
  customers-api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Services/CustomerService/Customers.API/Dockerfile
    ports:
      - "5103:80"
      - "50001:50001" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://brainykatseq
    depends_on:
      - brainykatsqldata
    

  customers-api-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "customers-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]
    network_mode: "service:customers-api"
    depends_on:
      - customers-api
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  finance-api:
    image: ${DOCKER_REGISTRY-}financeapi
    build:
      context: .
      dockerfile: src/Services/FinanceService/Finance.API/Dockerfile
    ports:
      - "5105:80"
      - "50003:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://brainykatseq
    depends_on:
      - brainykatsqldata
  
  finance-api-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "finance-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/brainykat-config.yaml"
      ]
    network_mode: "service:finance-api"
    depends_on:
      - finance-api
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  dapr-placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"



  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

volumes:
  brainykat-sqldata:
    external: false


