apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: brainydapr-secretstore
  #namespace: eshop
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/brainykat-secrets.json
  - name: nestedSeparator
    value: ":"